"""feat: add unified schema with server defaults

Revision ID: e11f906a6487
Revises: 
Create Date: 2026-03-25 21:50:33.553928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e11f906a6487'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_races_id'), table_name='races')
    op.drop_table('races')
    op.add_column('users', sa.Column('last_equipped_skin', sa.String(length=50), server_default='default', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_equipped_skin')
    op.create_table('races',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('wpm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('mode', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('races_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('races_pkey'))
    )
    op.create_index(op.f('ix_races_id'), 'races', ['id'], unique=False)
    # ### end Alembic commands ###
